Feature/vident components: Reader and Retriever
platiagro/tasks pull request #121
Opened 2021-10-21 18:22 UTC by lucasns97

Add Reader and Retriever component files.
- task
- test
- update readme
- update config.json
- workflow files

2021-10-29 18:30 UTC, andreluiz27 requested changes
Boa tarde Lucas!, Separei um tempinho pra dá uma olhada no seu PR, achei o código bem legível e bem coeso, entretanto há alguns code smells que merecem a devida atenção

2021-10-29 18:30 UTC, andreluiz27 commented on tasks/retriever/models/bm25.py
> +    def _calculate_similarities(self, hypothesis_sentences: List[str], reference_sentece: str) -> float:
Esse trecho de código está tipado para voltar um float, mas o retorno dela é um np.array

2021-10-29 18:30 UTC, andreluiz27 commented on tasks/retriever/models/bm25.py
> +        return batch_similarities
Aqui está retornando uma lista, porém você tipou um float como retorno.

2021-10-29 18:30 UTC, andreluiz27 commented on tasks/retriever/models/paraphrase_multilingual.py
> +# from time import time
Em termos de boas práticas, é recomendável evitar o envio de código comentado.

2021-11-03 11:48 UTC, lucasns97 commented on tasks/retriever/models/paraphrase_multilingual.py
> +# from time import time
Obrigado @andreluiz27 fiz as alterações, ambas de código comentado e tipagem das variáveis (que estavam incorretas) na definição das funções.

2021-11-09 14:13 UTC, merged