Features/wordcloud
platiagro/tasks pull request #123
Opened 2021-11-01 14:06 UTC by vitoryeso

Componente WordCloud. Pode receber textos em .csv ou apenas string. Possui alguns parâmetros como stopwords, max_words, background_color e etc. Também foram adicionados testes para esse componente.

2021-11-08 15:02 UTC, gvechini commented
Para todos os experiments, os títulos e descrições das seções poderiam ser mais claros e direcioandos para essa tarefa das componentes específicas, wordcould e pdf_extractor, eles estão como no defult de uma tarefa em branco.

Para todos os deployment, o titulo está como "Nova Tarefa - Implantação" e o texto está como "Preencha aqui com detalhes sobre a tarefa". Sugiro deixar esse header igual ao dos respectivos experiments.
No deploy de pdf_extractor tbm é preciso limpar os outputs, também seria melhor remover a última célula #testing.

2021-11-08 15:03 UTC, gvechini commented
No experiment do wordclous suba o aquivo com os outputs limpos.
No tópico "Leitura do conjunto de dados" a saída "data" tende a ser um vetor/coluna de csv bem grande né? Seria interessante mostrar só uma parte ou nem mostrar essa variável.



No experiment de pdf_extractor suba também o arquivo com os outputs limpos. Note que há uma caixinha de código não ultiliazda no final.
No tópico "Extraindo texto" você importa a função PDFExtractor e não ultiliza ela nesta célula, recomendo retirar essa chamada.

2021-11-22 18:12 UTC, lucasns97 commented on tasks/pdf-extractor/pdf_extractor.py
> +def init_cut(string:str, delimiter: str):
Seria interessante adicionar um docstring explicando o que este método faz.

2021-11-22 18:15 UTC, lucasns97 commented on tasks/pdf-extractor/pdf_extractor.py
> +def read_memory(stream,
Adicionar um docstring explicitando o que cada variável representa seria interessante.

Ex:
```
'''
Lê e pré processa os dados de um stream...

Parameters:
=========

    stream (tipo): Descrição...
    ... 
'''
```

2021-11-22 18:18 UTC, lucasns97 commented on tests/datasets.py
> +    return dat
Isso gerou um erro em outros componentes. O correto anteriormente escrito era `return data`

2021-11-25 12:35 UTC, lucasns97 requested changes
Mencionei um ponto que está causando erro em outras tasks; e esta PR está causando conflito com o datasets.py, precisam ser resolvidos antes do merge

2025-04-20 13:53 UTC, closed without merging