Feature/remove rows
platiagro/tasks pull request #149
Opened 2022-07-28 16:39 UTC by GabrielTalasso

2022-07-28 17:33 UTC, gvechini commented
Creio que não precisa desse arquivo novo, .Rhistory, retiele ele por favor.

2022-07-28 17:33 UTC, gvechini requested changes

2022-07-28 17:33 UTC, gvechini commented on tasks/remove-rows/Experiment.ipynb
> +   "execution_count": 1,
Lembrar de dar restart no notebook antes de subir para o git.

2022-07-29 10:58 UTC, gregorylira requested changes
tenta resetar o notebook, pra n subir com os output

2022-07-29 12:42 UTC, gregorylira approved these changes
agora está certinho

2022-07-29 18:28 UTC, gvechini approved these changes

2022-08-01 16:02 UTC, merged