Update test_kmeans_clustering.py
platiagro/tasks pull request #55
Opened 2021-03-25 17:21 UTC by gvechini

add filter_type/model_features and remove target

2021-03-25 22:56 UTC, fberanizo requested changes
Oi, @gvechini !
Tava com uma instabilidade, mas deu pra rodar os testes de novo.
Olha os comentários amanhã, por favor :)

2021-03-25 22:56 UTC, fberanizo commented on tests/test_isolation_forest_clustering.py
> +                model_features = "medv",
@gvechini parece que apesar do `filter_type` o Deployment continua retornando uma coluna a mais no deployment :(
https://github.com/platiagro/tasks/pull/55/checks?check_run_id=2196260066
![image](https://user-images.githubusercontent.com/1791381/112553089-a0fbb180-8da2-11eb-914d-ea4077f76002.png)

2021-03-25 22:56 UTC, fberanizo commented on tests/test_kmeans_clustering.py
> +                model_features = "Species",
@gvechini no kmeans deu este erro:
https://github.com/platiagro/tasks/runs/2197592726?check_suite_focus=true
![image](https://user-images.githubusercontent.com/1791381/112553856-08fec780-8da4-11eb-98dd-54eb2ad537f7.png)

2021-03-26 13:31 UTC, fberanizo commented on tests/test_isolation_forest_clustering.py
> +                model_features = "medv",
> @gvechini parece que apesar do `filter_type` o Deployment continua retornando uma coluna a mais no isolation forest:(

Ah, agora que me toquei que essa coluna a mais é o anomaly_score.  
O que precisa arrumar são esses testes:
```
self.assertEqual(len(ndarray[0]), 14)  # 13 features  + 1 anomaly score
self.assertEqual(len(names), 14)
```

e a mesma coisa pros outros test_...

2021-03-26 17:07 UTC, gvechini commented on tests/test_isolation_forest_clustering.py
> +                model_features = "medv",
Arrumei todos os testes :)

2021-03-26 17:13 UTC, gvechini commented
@fberanizo no test do kmeans tbm tem que adicioanr + Clusters nas quantidade de features, já vou corrigir.

2021-03-26 18:05 UTC, fberanizo approved these changes
👍

2021-03-26 18:05 UTC, merged